name: 06-contexts
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false

run-name: "My custom workflow run name | debug - ${{ github.event.inputs.debug }}"
env:
  MY_WORKFLOW_VAR: "workflow"
  MY_OVERWRITTEN_VAR: "workflow"
jobs:

  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "job"
      MY_OVERWRITTEN_VAR: "job"
    steps:
      - name: Display information
        run: |
          echo "The event name is: ${{ github.event_name }}"
          echo "The workflow name is: ${{ github.workflow }}"
          echo "The actor is: ${{ github.actor }}"
          echo "The repository is: ${{ github.repository }}"
          echo "The ref is: ${{ github.ref }}"
          echo "The sha is: ${{ github.sha }}"
          echo "The run number is: ${{ github.run_number }}"

      - name: Retrieve Variable
        run: |
          echo "The value of MY_VARIABLE is: ${{ vars.MY_VAR }}"
      - name: 
     