name: 06-contexts
on:
  workflow_dispatch:

env:
  MY_VARIABLE: "Hello, World!"

jobs:

  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display information
        run: |
          echo "The event name is: ${{ github.event_name }}"
          echo "The workflow name is: ${{ github.workflow }}"
          echo "The actor is: ${{ github.actor }}"
          echo "The repository is: ${{ github.repository }}"
          echo "The ref is: ${{ github.ref }}"
          echo "The sha is: ${{ github.sha }}"
          echo "The run number is: ${{ github.run_number }}"

      - name: Retrieve Variable
        run: echo "The value of MY_VARIABLE is: ${{ env.MY_VARIABLE }}"
     