name:  07 - Using Expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ github.event.inputs.debug }}
        run: |
          echo "Debug mode is enabled"
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow name: ${{ github.workflow }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Run number: ${{ github.run_number }}"
      - name: "[debug] Print when triggered"
        if: ${{ github.event.inputs.debug && github.ref == 'refs/heads/main'}}"
        run: echo "I was triggered from main"
      - name: "Greeting"
        run: echo "Hello, ${{ github.actor }}! Welcome to the world of GitHub Actions."