name: 09-Using Functions
on: [workflow_dispatch, pull_request]
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      # - name: Failing step  
      #   run: exit 1
       

      - name: I will be skipped
        run: echo "I will print if previous steps succeed."

      - name: I will execute
        run: echo "I will print if previous steps succeed"

      - name: I will execute when cancelled
        if: cancelled()
        run: echo "I will print if the workflow is cancelled."

      - name:  Sleep for 20 seconds
        run: sleep 20
      
      - name: Print PR title
        if: github.event_name == 'pull_request'
        run: |
          echo "The PR title is: ${{ github.event.pull_request.title }}"

      - name: Print PR Labels
        if: github.event_name == 'pull_request'
        run: |
          echo "The PR labels are:"
          for label in "${{ toJson(github.event.pull_request.labels)  }}"; do
            echo "$label"
          done
      
      # - name: bug step
      #   if: ${{ toJson(github.event.pull_request.labels) }} 