name: 09-Using Functions
on: [workflow_dispatch, pull_request]
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step  
        run: exit 1
       

      - name: I will be skipped
        run: echo "I will print if previous steps succeed."

      - name: I will execute
        run: echo "I will print if previous steps succeed"

      - name: I will execute when cancelled
        if: cancelled()
        run: echo "I will print if the workflow is cancelled."